server:
  port: 8082

spring:
  datasource:
    username: root
    password: password
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:/data/demo;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      format-sql: true
      ddl-auto: create-drop
      
logging:
 level:
   org.springframework.jdbc.core.JdbcTemplate: DEBUG
   org.springframework.jdbc.core.StatementCreatorUtils: TRACE
   org.springframework.security: DEBUG
   org.springframework.security.oauth2: DEBUG
   org.hibernate:
     SQL: DEBUG
     type.descriptor.sql.BasicBinder: TRACE