
spring:
  datasource:
    username: root
    password: password
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:/data/demo_test;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      format-sql: true
      ddl-auto: create


logging:
 level:
   org:
    springframework.jdbc.core.JdbcTemplate: DEBUG
    springframework.jdbc.core.StatementCreatorUtils: TRACE
    springframework.security: DEBUG
    springframework.security.oauth2: DEBUG
    hibernate:
     SQL: DEBUG
     type.descriptor.sql.BasicBinder: TRACE